version: "3"
services:
  cloud:
    image: potato9527/light-cloud:latest
    volumes:
      - light-cloud-data:/var/light_cloud/data
    ports:
      - "80:80"
    environment:
      - LIGHT_CLOUD_ACCOUNT=root
      - LIGHT_CLOUD_PWD=123456

volumes:
  light-cloud-data:
